### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by BarbzYHOOL** [exlinc/mdlr#2]
This looks rad.
Too bad I won't be able to help since it's in GO (why not a simple bash, or python?).

But I think I'm going to use this, I'm new to submodules but that looks like it will ease the work and I really love the "Info: git command ran". But why "INFO[00000]"?

Is it useable completely? or still in beta or something?

Also how to uninstall it?

**Comment by BarbzYHOOL** [comment]
Yeah, I guessed so for the uninstallation

And I use it on Linux.

A slightly offtopic question: why did you choose to use git submodules instead of subtree (or even subrepo)?

**Comment by svarlamov** [comment]
@BarbzYHOOL Sorry for the late response! We found it quite challenging to work with subtree and also when we started this project (quite a while before the first open source commits) there wasn't much support around for it

**Comment by svarlamov** [comment]
I believe that it also depends on your specific use case -- we were really looking for a single file approach, similar to something like a `package.json` for NodeJS projects, but for everything on Git
