### ISSUE TITLE
Using submodules command?

### ISSUE THREAD

**Issue by BarbzYHOOL** [exlinc/mdlr#4]
Can I use submodules command?

I did exactly like on the video, then I typed "git submodule status" but there is an error:

```
fatal: no submodule mapping found in .gitmodules for path `subrepo`
```

**Comment by svarlamov** [comment]
Sorry if that wasn't clear -- this is not a wrapper _around_ the `git submodule` command. It is a replacement and defines the modules in the `mdlr.yml` file. If you want to add a small script to your project to pull without having `mdlr` installed, then you could likely do it very simply by just reading that YML file

**Comment by BarbzYHOOL** [comment]
Ah k

**Comment by BarbzYHOOL** [comment]
But it's still considered a submodule no? because it kinds of act similarly, also I can use some commands like `git rev-parse --show-superproject-working-tree`
